return {
  None              = "NONE",
  Debug             = "#FF00FF",
--  Comment           = "#435f37",
  Comment           = "#405c37",
  Parameter         = "#9a9a9a",
  Type              = "#4EC9B0",
  Construtor        = "#4EC9B0",
  Namespace         = "#cffae4",
  Global            = "#F8D1EF",
  Property          = "#DADADA",
  SelfParameter     = "#CAC4FF",
  Numeric           = "#b5cea8",
  Invalid           = "#f44747",
  MacroFunction     = "#cac4ff",
  Macro             = "#bbafff",
  Normal            = "#DADADA",
  Preprocessor      = "#9b9b9b",
  Keyword           = "#569CD6",
  VariableLocal     = "#9CDCFE",
  Variable          = "#9CDCFE",
  VariableBuiltin   = "#2369a2",
  ControlFlow       = "#C586C0",
  Method            = "#DCDCAA",
  Native            = "#D7BA7D",
  Special           = "#D7BA7D",
}
